version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./api_zalo_shop:/var/www/api_zalo_shop
      - ./trasua-wp:/var/www/trasua-wp
    depends_on:
      - laravel
      - wordpress
    networks:
      - app_network
    extra_hosts:
      - "api.trasua.local:127.0.0.1"
      - "trasua.local:127.0.0.1"

  mysql:
    image: "mariadb:10.2"
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trasua
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - app_network

  laravel:
    build:
      context: ./api_zalo_shop
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always

    volumes:
      - ./api_zalo_shop:/var/www/api_zalo_shop
      - ./php/local.ini:/usr/local/etc/php/php.ini

    depends_on:
      - mysql
    networks:
      - app_network

  wordpress:
    build:
      context: ./trasua-wp
      dockerfile: Dockerfile    
    container_name: wordpress_site
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: trasua
    volumes:
      - ./trasua-wp:/var/www/trasua-wp
      - ./php/local.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    networks:
      - app_network
volumes:
  mysql_data:


networks:
  app_network:
    driver: bridge
